namespace BeamCustomPart
{
    partial class BeamCustomPartForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.okApplyModifyGetOnOffCancel1 = new Tekla.Structures.Dialog.UIControls.OkApplyModifyGetOnOffCancel();
            this.saveLoad1 = new Tekla.Structures.Dialog.UIControls.SaveLoad();
            this.lengthFactorLabel = new System.Windows.Forms.Label();
            this.textBoxProfile = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.profileCatalog1 = new Tekla.Structures.Dialog.UIControls.ProfileCatalog();
            this.textBoxLengthFactor = new System.Windows.Forms.TextBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.atDepthCcomboBox = new System.Windows.Forms.ComboBox();
            this.rotationComboBox = new System.Windows.Forms.ComboBox();
            this.onPlaneComboBox = new System.Windows.Forms.ComboBox();
            this.label4 = new System.Windows.Forms.Label();
            this.atDepthTextBox = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.rotationTextBox = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.onPlaneTextBox = new System.Windows.Forms.TextBox();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // okApplyModifyGetOnOffCancel1
            // 
            this.structuresExtender.SetAttributeName(this.okApplyModifyGetOnOffCancel1, null);
            this.structuresExtender.SetAttributeTypeName(this.okApplyModifyGetOnOffCancel1, null);
            this.structuresExtender.SetBindPropertyName(this.okApplyModifyGetOnOffCancel1, null);
            this.okApplyModifyGetOnOffCancel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.okApplyModifyGetOnOffCancel1.Location = new System.Drawing.Point(0, 302);
            this.okApplyModifyGetOnOffCancel1.Margin = new System.Windows.Forms.Padding(5);
            this.okApplyModifyGetOnOffCancel1.Name = "okApplyModifyGetOnOffCancel1";
            this.okApplyModifyGetOnOffCancel1.Size = new System.Drawing.Size(692, 36);
            this.okApplyModifyGetOnOffCancel1.TabIndex = 0;
            this.okApplyModifyGetOnOffCancel1.OkClicked += new System.EventHandler(this.okApplyModifyGetOnOffCancel1_OkClicked);
            this.okApplyModifyGetOnOffCancel1.ApplyClicked += new System.EventHandler(this.okApplyModifyGetOnOffCancel1_ApplyClicked);
            this.okApplyModifyGetOnOffCancel1.ModifyClicked += new System.EventHandler(this.okApplyModifyGetOnOffCancel1_ModifyClicked);
            this.okApplyModifyGetOnOffCancel1.GetClicked += new System.EventHandler(this.okApplyModifyGetOnOffCancel1_GetClicked);
            this.okApplyModifyGetOnOffCancel1.OnOffClicked += new System.EventHandler(this.okApplyModifyGetOnOffCancel1_OnOffClicked);
            this.okApplyModifyGetOnOffCancel1.CancelClicked += new System.EventHandler(this.okApplyModifyGetOnOffCancel1_CancelClicked);
            // 
            // saveLoad1
            // 
            this.structuresExtender.SetAttributeName(this.saveLoad1, null);
            this.structuresExtender.SetAttributeTypeName(this.saveLoad1, null);
            this.saveLoad1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.structuresExtender.SetBindPropertyName(this.saveLoad1, null);
            this.saveLoad1.Dock = System.Windows.Forms.DockStyle.Top;
            this.saveLoad1.HelpFileType = Tekla.Structures.Dialog.UIControls.SaveLoad.HelpFileTypeEnum.General;
            this.saveLoad1.HelpKeyword = "";
            this.saveLoad1.HelpUrl = "";
            this.saveLoad1.Location = new System.Drawing.Point(0, 0);
            this.saveLoad1.Margin = new System.Windows.Forms.Padding(5);
            this.saveLoad1.Name = "saveLoad1";
            this.saveLoad1.SaveAsText = "";
            this.saveLoad1.Size = new System.Drawing.Size(692, 53);
            this.saveLoad1.TabIndex = 1;
            this.saveLoad1.UserDefinedHelpFilePath = null;
            // 
            // lengthFactorLabel
            // 
            this.structuresExtender.SetAttributeName(this.lengthFactorLabel, null);
            this.structuresExtender.SetAttributeTypeName(this.lengthFactorLabel, null);
            this.lengthFactorLabel.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.lengthFactorLabel, null);
            this.lengthFactorLabel.Location = new System.Drawing.Point(8, 68);
            this.lengthFactorLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lengthFactorLabel.Name = "lengthFactorLabel";
            this.lengthFactorLabel.Size = new System.Drawing.Size(92, 17);
            this.lengthFactorLabel.TabIndex = 3;
            this.lengthFactorLabel.Text = "Length factor";
            // 
            // textBoxProfile
            // 
            this.structuresExtender.SetAttributeName(this.textBoxProfile, "Profile");
            this.structuresExtender.SetAttributeTypeName(this.textBoxProfile, "String");
            this.structuresExtender.SetBindPropertyName(this.textBoxProfile, null);
            this.textBoxProfile.Location = new System.Drawing.Point(252, 28);
            this.textBoxProfile.Margin = new System.Windows.Forms.Padding(4);
            this.textBoxProfile.Name = "textBoxProfile";
            this.textBoxProfile.Size = new System.Drawing.Size(132, 22);
            this.textBoxProfile.TabIndex = 2;
            // 
            // label1
            // 
            this.structuresExtender.SetAttributeName(this.label1, null);
            this.structuresExtender.SetAttributeTypeName(this.label1, null);
            this.label1.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label1, null);
            this.label1.Location = new System.Drawing.Point(8, 32);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(48, 17);
            this.label1.TabIndex = 3;
            this.label1.Text = "Profile";
            // 
            // tabControl1
            // 
            this.structuresExtender.SetAttributeName(this.tabControl1, null);
            this.structuresExtender.SetAttributeTypeName(this.tabControl1, null);
            this.structuresExtender.SetBindPropertyName(this.tabControl1, null);
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 53);
            this.tabControl1.Margin = new System.Windows.Forms.Padding(4);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(692, 249);
            this.tabControl1.TabIndex = 4;
            // 
            // tabPage1
            // 
            this.structuresExtender.SetAttributeName(this.tabPage1, null);
            this.structuresExtender.SetAttributeTypeName(this.tabPage1, null);
            this.structuresExtender.SetBindPropertyName(this.tabPage1, null);
            this.tabPage1.Controls.Add(this.profileCatalog1);
            this.tabPage1.Controls.Add(this.textBoxLengthFactor);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this.lengthFactorLabel);
            this.tabPage1.Controls.Add(this.textBoxProfile);
            this.tabPage1.Location = new System.Drawing.Point(4, 25);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(4);
            this.tabPage1.Size = new System.Drawing.Size(684, 220);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Parameters";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // profileCatalog1
            // 
            this.structuresExtender.SetAttributeName(this.profileCatalog1, null);
            this.structuresExtender.SetAttributeTypeName(this.profileCatalog1, null);
            this.profileCatalog1.BackColor = System.Drawing.Color.Transparent;
            this.structuresExtender.SetBindPropertyName(this.profileCatalog1, null);
            this.profileCatalog1.Location = new System.Drawing.Point(426, 28);
            this.profileCatalog1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.profileCatalog1.Name = "profileCatalog1";
            this.profileCatalog1.SelectedProfile = "";
            this.profileCatalog1.Size = new System.Drawing.Size(88, 22);
            this.profileCatalog1.TabIndex = 5;
            this.profileCatalog1.SelectClicked += new System.EventHandler(this.profileCatalog1_SelectClicked);
            this.profileCatalog1.SelectionDone += new System.EventHandler(this.profileCatalog1_SelectionDone);
            // 
            // textBoxLengthFactor
            // 
            this.structuresExtender.SetAttributeName(this.textBoxLengthFactor, "LengthFactor");
            this.structuresExtender.SetAttributeTypeName(this.textBoxLengthFactor, "Double");
            this.structuresExtender.SetBindPropertyName(this.textBoxLengthFactor, null);
            this.textBoxLengthFactor.Location = new System.Drawing.Point(252, 68);
            this.textBoxLengthFactor.Margin = new System.Windows.Forms.Padding(4);
            this.textBoxLengthFactor.Name = "textBoxLengthFactor";
            this.textBoxLengthFactor.Size = new System.Drawing.Size(132, 22);
            this.textBoxLengthFactor.TabIndex = 4;
            // 
            // tabPage2
            // 
            this.structuresExtender.SetAttributeName(this.tabPage2, null);
            this.structuresExtender.SetAttributeTypeName(this.tabPage2, null);
            this.structuresExtender.SetBindPropertyName(this.tabPage2, null);
            this.tabPage2.Controls.Add(this.atDepthCcomboBox);
            this.tabPage2.Controls.Add(this.rotationComboBox);
            this.tabPage2.Controls.Add(this.onPlaneComboBox);
            this.tabPage2.Controls.Add(this.label4);
            this.tabPage2.Controls.Add(this.atDepthTextBox);
            this.tabPage2.Controls.Add(this.label3);
            this.tabPage2.Controls.Add(this.rotationTextBox);
            this.tabPage2.Controls.Add(this.label2);
            this.tabPage2.Controls.Add(this.onPlaneTextBox);
            this.tabPage2.Location = new System.Drawing.Point(4, 25);
            this.tabPage2.Margin = new System.Windows.Forms.Padding(4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(4);
            this.tabPage2.Size = new System.Drawing.Size(684, 220);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Positions";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // atDepthCcomboBox
            // 
            this.structuresExtender.SetAttributeName(this.atDepthCcomboBox, "AtDepth");
            this.structuresExtender.SetAttributeTypeName(this.atDepthCcomboBox, "Integer");
            this.structuresExtender.SetBindPropertyName(this.atDepthCcomboBox, "SelectedIndex");
            this.atDepthCcomboBox.FormattingEnabled = true;
            this.atDepthCcomboBox.Items.AddRange(new object[] {
            "Middle",
            "Front",
            "Behind"});
            this.atDepthCcomboBox.Location = new System.Drawing.Point(223, 87);
            this.atDepthCcomboBox.Margin = new System.Windows.Forms.Padding(4);
            this.atDepthCcomboBox.Name = "atDepthCcomboBox";
            this.atDepthCcomboBox.Size = new System.Drawing.Size(116, 24);
            this.atDepthCcomboBox.TabIndex = 12;
            // 
            // rotationComboBox
            // 
            this.structuresExtender.SetAttributeName(this.rotationComboBox, "Rotation");
            this.structuresExtender.SetAttributeTypeName(this.rotationComboBox, "Integer");
            this.structuresExtender.SetBindPropertyName(this.rotationComboBox, "SelectedIndex");
            this.rotationComboBox.FormattingEnabled = true;
            this.rotationComboBox.Items.AddRange(new object[] {
            "Front",
            "Top",
            "Back",
            "Below"});
            this.rotationComboBox.Location = new System.Drawing.Point(223, 55);
            this.rotationComboBox.Margin = new System.Windows.Forms.Padding(4);
            this.rotationComboBox.Name = "rotationComboBox";
            this.rotationComboBox.Size = new System.Drawing.Size(116, 24);
            this.rotationComboBox.TabIndex = 11;
            // 
            // onPlaneComboBox
            // 
            this.structuresExtender.SetAttributeName(this.onPlaneComboBox, "OnPlane");
            this.structuresExtender.SetAttributeTypeName(this.onPlaneComboBox, "Integer");
            this.structuresExtender.SetBindPropertyName(this.onPlaneComboBox, "SelectedIndex");
            this.onPlaneComboBox.FormattingEnabled = true;
            this.onPlaneComboBox.Items.AddRange(new object[] {
            "Middle",
            "Right",
            "Left"});
            this.onPlaneComboBox.Location = new System.Drawing.Point(223, 23);
            this.onPlaneComboBox.Margin = new System.Windows.Forms.Padding(4);
            this.onPlaneComboBox.Name = "onPlaneComboBox";
            this.onPlaneComboBox.Size = new System.Drawing.Size(116, 24);
            this.onPlaneComboBox.TabIndex = 10;
            // 
            // label4
            // 
            this.structuresExtender.SetAttributeName(this.label4, null);
            this.structuresExtender.SetAttributeTypeName(this.label4, null);
            this.label4.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label4, null);
            this.label4.Location = new System.Drawing.Point(23, 91);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(61, 17);
            this.label4.TabIndex = 9;
            this.label4.Text = "At depth";
            // 
            // atDepthTextBox
            // 
            this.structuresExtender.SetAttributeName(this.atDepthTextBox, "AtDepthValue");
            this.structuresExtender.SetAttributeTypeName(this.atDepthTextBox, "Distance");
            this.structuresExtender.SetBindPropertyName(this.atDepthTextBox, null);
            this.atDepthTextBox.Location = new System.Drawing.Point(348, 87);
            this.atDepthTextBox.Margin = new System.Windows.Forms.Padding(4);
            this.atDepthTextBox.Name = "atDepthTextBox";
            this.atDepthTextBox.Size = new System.Drawing.Size(221, 22);
            this.atDepthTextBox.TabIndex = 8;
            // 
            // label3
            // 
            this.structuresExtender.SetAttributeName(this.label3, null);
            this.structuresExtender.SetAttributeTypeName(this.label3, null);
            this.label3.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label3, null);
            this.label3.Location = new System.Drawing.Point(23, 59);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(61, 17);
            this.label3.TabIndex = 7;
            this.label3.Text = "Rotation";
            // 
            // rotationTextBox
            // 
            this.structuresExtender.SetAttributeName(this.rotationTextBox, "RotationValue");
            this.structuresExtender.SetAttributeTypeName(this.rotationTextBox, "Double");
            this.structuresExtender.SetBindPropertyName(this.rotationTextBox, null);
            this.rotationTextBox.Location = new System.Drawing.Point(348, 55);
            this.rotationTextBox.Margin = new System.Windows.Forms.Padding(4);
            this.rotationTextBox.Name = "rotationTextBox";
            this.rotationTextBox.Size = new System.Drawing.Size(221, 22);
            this.rotationTextBox.TabIndex = 6;
            // 
            // label2
            // 
            this.structuresExtender.SetAttributeName(this.label2, null);
            this.structuresExtender.SetAttributeTypeName(this.label2, null);
            this.label2.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label2, null);
            this.label2.Location = new System.Drawing.Point(23, 27);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(66, 17);
            this.label2.TabIndex = 5;
            this.label2.Text = "On plane";
            // 
            // onPlaneTextBox
            // 
            this.structuresExtender.SetAttributeName(this.onPlaneTextBox, "OnPlaneValue");
            this.structuresExtender.SetAttributeTypeName(this.onPlaneTextBox, "Distance");
            this.structuresExtender.SetBindPropertyName(this.onPlaneTextBox, null);
            this.onPlaneTextBox.Location = new System.Drawing.Point(348, 23);
            this.onPlaneTextBox.Margin = new System.Windows.Forms.Padding(4);
            this.onPlaneTextBox.Name = "onPlaneTextBox";
            this.onPlaneTextBox.Size = new System.Drawing.Size(221, 22);
            this.onPlaneTextBox.TabIndex = 4;
            // 
            // BeamCustomPartForm
            // 
            this.structuresExtender.SetAttributeName(this, null);
            this.structuresExtender.SetAttributeTypeName(this, null);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.structuresExtender.SetBindPropertyName(this, null);
            this.ClientSize = new System.Drawing.Size(692, 338);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.saveLoad1);
            this.Controls.Add(this.okApplyModifyGetOnOffCancel1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "BeamCustomPartForm";
            this.Text = "BeamPluginForm";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Tekla.Structures.Dialog.UIControls.OkApplyModifyGetOnOffCancel okApplyModifyGetOnOffCancel1;
        private Tekla.Structures.Dialog.UIControls.SaveLoad saveLoad1;
        private System.Windows.Forms.Label lengthFactorLabel;
        private System.Windows.Forms.TextBox textBoxProfile;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox onPlaneTextBox;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox rotationTextBox;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox atDepthTextBox;
        private System.Windows.Forms.ComboBox onPlaneComboBox;
        private System.Windows.Forms.ComboBox atDepthCcomboBox;
        private System.Windows.Forms.ComboBox rotationComboBox;
        private System.Windows.Forms.TextBox textBoxLengthFactor;
        private Tekla.Structures.Dialog.UIControls.ProfileCatalog profileCatalog1;

    }
}

