// Generated by Tekla.Technology.Akit.ScriptBuilder
using System;
using System.IO;
using Tekla.Structures.Model;

namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            Model Model1 = new Model();
            string modelpath = Model1.GetInfo().ModelPath;
            string CNC_settingsname = "standard";
            string Plot_directoryname = "Unknown";
            string CNC_Files = "CNCData";

            if (File.Exists(modelpath + @"\CNCProps.txt"))
            {
                StreamReader SR1 = new StreamReader(modelpath + @"\CNCProps.txt");
                CNC_settingsname = SR1.ReadLine();
                Plot_directoryname =SR1.ReadLine();
                CNC_Files = SR1.ReadLine();
                SR1.Close();
            }
            // Load the CNC settings that are saved away that you want the program to cycle through. Make sure the settings you want Tekla to run are checked.
            akit.ValueChange("diaNCFilesDialog", "get_menu", CNC_settingsname);
            akit.PushButton("attrib_get", "diaNCFilesDialog");
            try
            {
                for (int i = 0; i <= 10; i++)
                {
                    akit.Callback("acmd_display_nc_dialog", "", "main_frame");
                    akit.TableSelect("diaNCFilesDialog", "tableNCFileSettings", i);
                    akit.PushButton("nc_files_pushbutton_edit", "diaNCFilesDialog");
                    akit.ValueChange("diaNCFileSettingsDialog", "FileLocationField", @".\" + Plot_directoryname + @"\" + CNC_Files);
                    akit.PushButton("pushbutton_426", "diaNCFileSettingsDialog");
                }
            }
            catch
            {

            }
            akit.ValueChange("diaNCFilesDialog", "PartsOption", "1");
            akit.PushButton("pushbutton_917", "diaNCFilesDialog");
            akit.PushButton("pushbutton_916", "diaNCFilesDialog");
        }
    }
}